Add blockchains
notifi-network/notifi-sdk-ts pull request #337
Opened 2023-06-16 21:32 UTC by kai-notifi

Add missing blockchains to sdk

2023-06-16 23:17 UTC, eric-notifi commented
Hey @kai-notifi Kai, Just checked the PR. OSMOSIS, EVMOS and OFF_CHAIN are added

If it is tend to add chains support, I guess there are some more places to add. I also have one [PR for supporting EVMOS](https://github.com/notifi-network/notifi-sdk-ts/pull/333/files) FYI. But at that time (two days ago), BE still not yet supports the EVMOS wallet source type, also not certain about the signMessage

2023-06-16 23:50 UTC, eric-notifi commented
Ah.... and I think we do not need to increase the version manually. Lerna will handle the version when we publish it.

2023-06-17 07:38 UTC, eric-notifi requested changes

2023-06-17 07:38 UTC, eric-notifi commented on packages/notifi-core/lib/models/WalletBlockchain.ts
> +  | 'EVMOS';
It might be better not to include the unsupported chains:
- OFF_CHAIN
- EVMOS
- OSMOSIS

2023-06-17 07:38 UTC, eric-notifi commented on packages/notifi-node/lib/types/WalletBlockchain.ts
> +  | 'EVMOS';
It might be better not to include the unsupported chains:
- OFF_CHAIN
- EVMOS
- OSMOSIS

2023-06-17 07:38 UTC, eric-notifi commented on packages/notifi-node-sample/package.json
> +    "@notifi-network/notifi-node": "^0.73.3",
Ah ... we might not need to manually modify the version. Lerna will handle version control when we publish it.

2023-06-17 07:38 UTC, eric-notifi commented on packages/notifi-node-sample/package.json
> +    "@notifi-network/notifi-node": "^0.73.3",
It adopts to all version related section below

2023-06-19 18:33 UTC, Haoqian-Zheng commented
lgtm!

2023-06-20 00:51 UTC, eric-notifi approved these changes
LGTM, Thanks!

2023-06-20 04:02 UTC, merged